name: Deploy to Google Play Store

on:
  workflow_dispatch:
    inputs:
      releaseTrack:
        description: 'The release track to deploy to (e.g., production, beta, alpha)'
        required: true
        default: 'production'
        type: choice
        options:
          - production
          - beta
          - alpha

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Download APK Artifact
        uses: actions/download-artifact@v3
        with:
          name: flutter-apk
          path: build

      - name: Set up Google Play credentials
        uses: google-github-actions/auth@v0
        with:
          credentials_json: ${{ secrets.GOOGLE_PLAY_SERVICE_ACCOUNT }}

      - name: Deploy to Google Play
        uses: r0adkll/upload-google-play@v1
        with:
          serviceAccountJson: ${{ secrets.GOOGLE_PLAY_SERVICE_ACCOUNT }}
          packageName: com.example.myapp
          releaseFile: build/app/outputs/flutter-apk/app-release.apk
          track: ${{ github.event.inputs.releaseTrack }}
