name: Build and Deploy Flutter APK to Azure Blob Storage

on:
  push:
    branches:
      - main  # Trigger on push to main
  workflow_dispatch:  # Allow manual trigger

jobs:
  build:
    name: Build APK and Upload to Azure
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout the code
    - name: Checkout code
      uses: actions/checkout@v3

    # Step 2: Set up Flutter
    - name: Set up Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: 3.19.5

    # Step 3: Install dependencies
    - name: Install dependencies
      run: flutter pub get

    # Step 4: Build APK
    - name: Build APK
      run: flutter build apk --release

    # Step 5: Log in to Azure
    - name: Login to Azure
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    # Step 6: Upload APK to Azure Blob Storage
    - name: Upload APK
      run: |
        az storage blob upload \
          --account-name ${{ secrets.AZURE_STORAGE_ACCOUNT_NAME }} \
          --container-name ${{ secrets.AZURE_STORAGE_CONTAINER_NAME }} \
          --file build/app/outputs/flutter-apk/app-release.apk \
          --name smartdoc.apk
